FROM node:20-alpine 

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY . .
copy .env .env

RUN if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi

EXPOSE 80

CMD npx prisma migrate dev --name initial_migratio && npx prisma db seed && npm run start
