services:
  backend-1:
    build: ../backend
    depends_on:
      - pg
    networks:
      - pg-compose-network
      - load-balancer
  
  frontend-1:
    build: ../frontend
    depends_on:
      - backend-1
    networks:
      - load-balancer
  pg:
    image: "postgres"
    environment:    
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=fullstack_week
    networks:
      - pg-compose-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5000:80"
    depends_on:
      - pg
    networks:
      - pg-compose-network
      - load-balancer

  nginx:
    build: ../nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend-1
      - frontend-1
    networks:
      - load-balancer
    volumes:
      - ../nginx/ssl:/etc/nginx/ssl/
networks: 
  pg-compose-network:
    driver: bridge
  load-balancer:
